### ISSUE TITLE
Server file checking bug

### ISSUE THREAD

**Issue by ripperma** [biolab/orange-bio#102]
version:
2.6.20

raised exception:
obiTaxonomy.UnknownSpeciesIdentifier

place:
bio/go.py line 782

problem:
serverfiles.ServerFiles().listfiles() was called before the exception
This returns a list of tuples (line 30 in serverfiles.py), e.g., [('GO', 'gene_as....tar.gz')]
This list was checked for 'filename' instead of a second tuple column list

**Comment by markotoplak** [comment]
Please try the newest version. 

If you installed the add-ons from Orange Canvas, just remove the addon and install it again. For a while the old version will be (wrongly) shown as the available one, but even if you install it now, you should get 2.6.21.
