### ISSUE TITLE
About file conversions

### ISSUE THREAD

**Issue by pslacerda** [biolab/orange-bio#30]
Hi,

I wanted to use some *.res files on Orange. It's similar to *.soft files but simpler, and it don't have anything like `!subset_description` to store class information. Nevertheless my code tries to extract classes from .res using simple regexes.

Please have a look on [res2tab.py](https://github.com/pslacerda/microarray-data-mining) and tell me if you like useful, it's somewhat similar to your scripts/geo2orange.py

**Comment by sunil-sangwan** [comment]
res2tab.py link is broken :(

**Comment by ajdapretnar** [comment]
@pslacerda Please submit a PR with the contribution if you still find it useful. We would be happy to review the code and comment on it. As for now, I'm closing the issue.
