### ISSUE TITLE
OBO ontologies end up undirected

### ISSUE THREAD

**Issue by xapple** [biolab/orange-bio#73]
Hi !

I was really happy to see a nice OBO ontology parser for python in your package and think it can be very useful. Of course the first thing I did was use the `to_networkx()` method to manipulate and calculate things on the graph. But the conversion seems to leave out some essential information:

```
In [1]: from orangecontrib.bio.ontology import OBOOntology
In [2]: onto = OBOOntology('/Users/xapple/seqenv/data/envo.obo')
In [3]: nwrk = onto.to_networkx()
In [4]: nwrk.is_directed()
Out[4]: False
```

**Comment by xapple** [comment]
Awesome, thanks for the fix. Can we expect this soon in the PyPI version, or do we have to clone from master ?

**Comment by ales-erjavec** [comment]
>  Awesome, thanks for the fix. Can we expect this soon in the PyPI version, or do we have to clone from master ?

The latest version from PyPi includes the fix.
